vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1 -- disable netrw to replace with nvim-tree
vim.cmd('language en_US')
vim.opt.clipboard = "unnamedplus"
vim.opt.completeopt = "menuone,noselect,noinsert"
vim.opt.conceallevel = 0
vim.opt.hidden = true -- for buffers
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.mouse = "a"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.termguicolors = true
vim.opt.undofile = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.scrolloff = 10
vim.opt.sidescrolloff = 10
